name: Laravel Pint Lint

on: [push, pull_request]

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: jalanin Laravel Pint untuk controller
        run: ./vendor/bin/pint src/app/Http/Controllers
        
      - name: jalanin Laravel Pint untuk controller admin
        run: ./vendor/bin/pint src/app/Http/Controllers/Admin

      - name: jalanin Laravel Pint untuk controller kaprodi
        run: ./vendor/bin/pint src/app/Http/Controllers/Kaprodi
